services:
  app:
    build: .
    container_name: migrate-app
    volumes:
      - ./activecollab:/var/www/html/app
      - .:/migrate
    networks:
      - migrate-activecollab

  mysql:
    image: mariadb:10.11
    container_name: migrate-db
    ports:
      - "3366:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 'root'
      MARIADB_DATABASE: 'activecollab'
    networks:
      - migrate-activecollab
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-flush-log-at-trx-commit=0
      - --innodb_buffer_pool_size=1G
      - --skip-log-bin
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

  phpmyadmin:
    container_name: migrate-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8889:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - migrate-activecollab

  nginx:
    image: nginx:latest
    container_name: migrate-nginx
    ports:
      - "8886:8886"
      - "8887:8887"
      - "8888:8888"
    volumes:
      - ./servers/ac6.conf:/etc/nginx/conf.d/ac6.conf
      - ./servers/ac7.conf:/etc/nginx/conf.d/ac7.conf
      - ./servers/ac8.conf:/etc/nginx/conf.d/ac8.conf
      - ./activecollab:/var/www/html/app
    extra_hosts:
      - "ac6.local:127.0.0.1"
      - "ac7.local:127.0.0.1"
      - "ac8.local:127.0.0.1"
    networks:
      - migrate-activecollab

networks:
  migrate-activecollab:
    driver: bridge
