[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:php74-fpm]
command=/opt/remi/php74/root/usr/sbin/php-fpm --nodaemonize --fpm-config /etc/opt/remi/php74/php-fpm.conf
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:php81-fpm]
command=/opt/remi/php81/root/usr/sbin/php-fpm --nodaemonize --fpm-config /etc/opt/remi/php81/php-fpm.conf
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=15

[program:php83-fpm]
command=/opt/remi/php83/root/usr/sbin/php-fpm --nodaemonize --fpm-config /etc/opt/remi/php83/php-fpm.conf
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20
