server {
  listen 8886;
  server_name localhost ac6.local;
  access_log /dev/stdout;
  error_log  /dev/stderr warn;
  set $root_path /var/www/html/app/activecollab/public;
  root $root_path;
  index index.html index.htm index.php router.php;
  charset utf-8;
  if (!-e $request_filename) {
    rewrite ^/assets/(.*)$ /assets/$1 last;
    rewrite ^/avatars/(.*)$ /avatars/$1 last;
    rewrite ^/wallpapers/(.*)$ /wallpapers/$1 last;
    rewrite ^/verify-existence$ /verify.php last;
    rewrite ^/proxy.php$ /proxy.php last;
    rewrite ^/api/v([0-9]*)/(.*)$ /api.php?path_info=$2&api_version=$1 last;
    rewrite ^$ /router.php last;
    rewrite ^(.*) /router.php?path_info=$1 last;
  }

  location / {
    rewrite ^/verify-existence$ /verify.php last;
    rewrite ^/proxy.php$ /proxy.php last;
    rewrite ^/api/v([0-9]*)/(.*)$ /api.php?path_info=$2&api_version=$1 last;
    rewrite ^/$ /router.php last;
    try_files $uri $uri/ /router.php?path_info=$uri&$args;
  }

  location ~ ^/(assets|avatars|wallpapers)/ {
    root $root_path;
  }

  location ~ .*\.php$ {
    fastcgi_index   index.php;
    fastcgi_pass    migrate-app:9004;
    include         fastcgi_params;
    fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
    fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
    fastcgi_buffering off;
    fastcgi_param   HTTP_IF_NONE_MATCH $http_if_none_match;
  }
}
